[project]
name = "yeardigits"
version = "0.1.0"
description = "Code practice calculating integers from the digits of a year."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
]
